spring:
  profiles:
    group:
      local:
        - local

      prod:
        - prod

    active: local
    include:
      - db


--- # local ?? -> ?? ??? ??? ? ??? ?? ??? ????. ??? ???? ?? ??? ???? ????.
spring:
  config:
    activate:
      on-profile: local
#server:
#  port: 8088

---
spring:
  config:
    activate:
      on-profile: prod